% This code is to build a linear regression model to inquiry the influence
% of specified variables on forecasting the growth of GDP as well as their
% significance, effect of different combinations and effect changing along
% the time period.

clc
clear all
close all
format bank;
format compact;

%% Import data

GDP = readtable('A191RL1Q225SBEA.xls');

%Total Dwellings and Residential Buildings by Stage of Construction, 
%Started for the United States, Growth Rate Previous Period, Quarterly, 
%Seasonally Adjusted
building = readtable('WSCNDW01USQ657S.xls');

%Real Gross Private Domestic Investment, Percent Change from 
%Preceding Period, Quarterly, Seasonally Adjusted Annual Rate
investment = readtable('A006RL1Q225SBEA.xls');

%Nonfarm Business Sector: Real Output Per Hour of All Persons, 
%Percent Change From Quarter One Year Ago, Quarterly, 
%Seasonally Adjusted
outputphour = readtable('PRS85006091.xls');

%% Model 1 : GDPgrowth ~ BuildingConstruct + OutputperHr + PrivateInvest

data_var3 = innerjoin(innerjoin(innerjoin(GDP,building),investment),outputphour);
T_var3 = length(data_var3.GDPgrowth);
data_var3.GDPgrowth4 = zeros(T_var3,1);
data_var3.GDPgrowth4(1:T_var3-3) = (data_var3.GDPgrowth(1:T_var3-3) + ...
                                                                    data_var3.GDPgrowth(2:T_var3-2) + ...
                                                                    data_var3.GDPgrowth(3:T_var3-1) + ...
                                                                    data_var3.GDPgrowth(4:T_var3))/4;
LM_var3_a = fitlm(data_var3(1:T_var3-3,:),...
                   'GDPgrowth4~BuildingConstruct + OutputperHr + PrivateInvest',...
                   'RobustOpts','on')
LM_var3_b = fitlm(data_var3(1:80,:),...
                    'GDPgrowth4~BuildingConstruct + OutputperHr + PrivateInvest',...
                    'RobustOpts','on')                                            
LM_var3_c = fitlm(data_var3(81:154,:),...
                    'GDPgrowth4~BuildingConstruct + OutputperHr + PrivateInvest',...
                    'RobustOpts','on')                                            
LM_var3_d = fitlm(data_var3(155:T_var3-3,:),...
                    'GDPgrowth4~BuildingConstruct + OutputperHr + PrivateInvest',...
                    'RobustOpts','on')                                            
%% Model 2 : GDPgrowth ~ BuildingConstruct
data_varB = innerjoin(GDP,building);
T_varB = length(data_varB.GDPgrowth);
data_varB.GDPgrowth4 = zeros(T_varB,1);
data_varB.GDPgrowth4(1:T_varB-3) = (data_varB.GDPgrowth(1:T_varB-3) + ...
                                                                    data_varB.GDPgrowth(2:T_varB-2) + ...
                                                                    data_varB.GDPgrowth(3:T_varB-1) + ...
                                                                    data_varB.GDPgrowth(4:T_varB))/4;
LM_varB_a = fitlm(data_varB(1:T_varB-3,:),...
                   'GDPgrowth4~BuildingConstruct',...
                   'RobustOpts','on')
LM_varB_b = fitlm(data_varB(1:80,:),...
                    'GDPgrowth4~BuildingConstruct',...
                    'RobustOpts','on')                                            
LM_varB_c = fitlm(data_varB(81:154,:),...
                    'GDPgrowth4~BuildingConstruct',...
                    'RobustOpts','on')
LM_varB_d = fitlm(data_varB(155:T_varB-3,:),...
                    'GDPgrowth4~BuildingConstruct',...
                    'RobustOpts','on')    
plot(data_varB.BuildingConstruct, data_varB.GDPgrowth4,'*');
grid on
xlabel('BuildingConstruct');
ylabel('GDPgrowth4');
title('GDPgrowth ~ BuildingConstruct');
%% Model 3 : GDPgrowth ~ OutputperHr                                            
data_varO = innerjoin(GDP,outputphour);
T_varO = length(data_varO.GDPgrowth);
data_varO.GDPgrowth4 = zeros(T_varO,1);
data_varO.GDPgrowth4(1:T_varO-3) = (data_varO.GDPgrowth(1:T_varO-3) + ...
                                                                    data_varO.GDPgrowth(2:T_varO-2) + ...
                                                                    data_varO.GDPgrowth(3:T_varO-1) + ...
                                                                    data_varO.GDPgrowth(4:T_varO))/4;
LM_varO_a = fitlm(data_varO(1:T_varO-3,:),...
                   'GDPgrowth4~OutputperHr',...
                   'RobustOpts','on')
LM_varO_b = fitlm(data_varO(1:80,:),...
                    'GDPgrowth4~OutputperHr',...
                    'RobustOpts','on')
LM_varO_c = fitlm(data_varO(81:154,:),...
                    'GDPgrowth4~OutputperHr',...
                    'RobustOpts','on')
LM_varO_d = fitlm(data_varO(155:T_varO-3,:),...
                    'GDPgrowth4~OutputperHr',...
                    'RobustOpts','on')
plot(data_varO.OutputperHr, data_varO.GDPgrowth4,'*');
grid on
xlabel('OutputperHr');
ylabel('GDPgrowth4');
title('GDPgrowth ~ OutputperHr');
%% Model 4 : GDPgrowth ~ PrivateInvest
data_varP = innerjoin(GDP,investment);
T_varP = length(data_varP.GDPgrowth);
data_varP.GDPgrowth4 = zeros(T_varP,1);
data_varP.GDPgrowth4(1:T_varP-3) = (data_varP.GDPgrowth(1:T_varP-3) + ...
                                                                    data_varP.GDPgrowth(2:T_varP-2) + ...
                                                                    data_varP.GDPgrowth(3:T_varP-1) + ...
                                                                    data_varP.GDPgrowth(4:T_varP))/4;
LM_varP_a = fitlm(data_varP(1:T_varP-3,:),...
                   'GDPgrowth4~PrivateInvest',...
                   'RobustOpts','on')
LM_varP_b = fitlm(data_varP(1:80,:),...
                    'GDPgrowth4~PrivateInvest',...
                    'RobustOpts','on')                                            
LM_varP_c = fitlm(data_varP(81:154,:),...
                    'GDPgrowth4~PrivateInvest',...
                    'RobustOpts','on')
LM_varP_d = fitlm(data_varP(155:T_varP-3,:),...
                    'GDPgrowth4~PrivateInvest',...
                    'RobustOpts','on')
plot(data_varP.PrivateInvest, data_varP.GDPgrowth4,'*');
grid on
xlabel('PrivateInvest');
ylabel('GDPgrowth4');
title('GDPgrowth ~ PrivateInvest');                
                
                
                
                
                
                
                
                
                
                